### ISSUE TITLE
Switchvox 6.6.0.x Changed Authentication Methods

### ISSUE THREAD

**Issue by voice1** [digium/PySwitchvox#2]
Switchvox update 6.6.0.x changed API authentication methods removing HTTPDigestAuth.
This change was undocumented on the release notes and was only uncovered on from an internal support ticket. Currently Digium has not release documentation or updated the SDK to match the changes making this SDK unusable on new installations.

I have submitted a patch to allow checking for supported authentication method and allow this SDK to remain viable. (see pull request)

**Comment by matt-jordan** [comment]
Thanks for the PR to fix this - I'm going to close out this issue to that PR.

https://github.com/digium/PySwitchvox/pull/1
